<form action="/forum/post/create/id/<?php echo $this->id;?>" method="post">
<table width="95%" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td width="36%" height="35" align="right">姓名：</td>
    <td width="64%" align="left"><input type="text" name="username" id="username" />    
    </td>
    </tr>
  <tr>
    <td height="35" align="right" valign="top" style="vertical-align:top;">内容：</td>
    <td ><textarea name="lestreily" id="lestreily" cols="45" rows="3"></textarea></td>
    </tr>
  <tr>
    <td height="35" colspan="2" align="center"><input type="submit" name="button" id="button" value="提交" />
      <input type="button" name="button2" id="button2" value="返回" onclick="javascript:history.go(-1);" /></td>
    </tr>
</table>
</form>