<form action="" method="post">
<table width="95%" border="0" align="center" cellpadding="0" cellspacing="0" style="font-size:16px;">
  <tr>
    <td width="30%" height="35" align="right">展示：</td>
    <td width="70%" colspan="2"><select name="showid" id="showid">
      <option id='1' <?php if($this->row['isshow']==1){echo "selected='selected'";}?>>显示</option>
      <option id='0' <?php if($this->row['isshow']==0){echo "selected='selected'";}?>>隐藏</option>
    </select>
    </td>
  </tr>
  <tr>
    <td height="35" align="right" valign="top" style="vertical-align:top;">内容：</td>
    <td colspan="2"><textarea name="issubject" id="issubject" cols="45" rows="3"><?php echo $this->row['content'];?></textarea></td>
  </tr>
  
  <tr>
    <td height="35" colspan="3" align="center"><input type="submit" name="button" id="button" value="提交" />
    <input type="button" name="button2" id="button2" value="返回" onclick="javascript:history.go(-1);" /></td>
  </tr>
</table>
</form>