<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
<title>留言管理系统</title>

<link rel="stylesheet" href="<?=Class_Server::extUrl()?>/reset.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="<?=Class_Server::libUrl()?>/style/admin.css" type="text/css" media="screen" rel="stylesheet">

<link rel="stylesheet" href="<?=Class_Server::extUrl()?>/admin/toolbar.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="<?=Class_Server::extUrl()?>/admin/links.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="<?=Class_Server::extUrl()?>/admin/head-desc.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="<?=Class_Server::extUrl()?>/admin/footer.css" type="text/css" media="screen, projection">

<script type="text/javascript" src="<?=Class_Server::extUrl()?>/jub.js"></script>
<script type="text/javascript" src="<?=Class_Server::extUrl()?>/ajax-select-grid.js"></script>

<script>
window.ORG_CODE = "<?php echo Class_Server::getOrgCode()?>";
</script>