<?php
//输出一个gif的图片
Header("Content-type: image/gif");
/*
* 初始化
*/          
//是否要边框 1要:0不要  
$border = 1;  
//验证码位数
$how = 4;          
//图片宽度
$w = $how*15+11;  
//图片高度
$h = 23;       
//字体大小
$fontsize = 5;                               
//验证码内容1
$alpha = "abcdefghijkmnpqrstujklmnstuvwxyz"; 
//验证码内容2
$number = "vwxyzabcdefgh2345pqr6789";  
//验证码字符串初始化
$randcode2 = "";                     
//初始化随机数种子
srand((double)microtime()*1000000); 
//创建验证图片
$im = ImageCreate($w, $h); 
/*
* 绘制基本框架
*/
//设置背景颜色
$bgcolor = ImageColorAllocate($im, 64, 64, 66); 
//填充背景色 
ImageFill($im, 0, 0, $bgcolor); 
if($border)
{                                                    
    //设置边框颜色
    $black = ImageColorAllocate($im, 0, 0, 0);         
    //绘制边框
    ImageRectangle($im, 0, 0, $w-1, $h-1, $black);
}
/*
* 逐位产生随机字符
*/
for($i=0; $i<$how; $i++)
{                                         
    //字母还是数字
    $alpha_or_number = mt_rand(0, 1); 
    $str = $alpha_or_number ? $alpha : $number;  
    //取哪个字符
    $which = mt_rand(0, strlen($str)-1); 
    //取字符
    $code = substr($str, $which, 1);  
    //绘字符位置
    $j = !$i ? 9 : $j+15;                                                                
    //字符随即颜色
    $color3 = ImageColorAllocate($im, mt_rand(240,255), mt_rand(240,255), mt_rand(240,255)); 
    ImageChar($im, $fontsize, $j, 3, $code, $color3); //绘字符
    $randcode2 .= $code; //逐位加入验证码字符串
}
for($i=0; $i<$how*30; $i++)//绘背景干扰点
{   
    $color2 = ImageColorAllocate($im, mt_rand(0,255), mt_rand(0,255), mt_rand(0,255)); //干扰点颜色 
    ImageSetPixel($im, mt_rand(0,$w), mt_rand(0,$h), $color2); //干扰点
}
//把验证码字符串写入session
//session_start();
$_SESSION['randcode'] = $randcode2;
/*绘图结束*/
imagegif($im);
imagedestroy($im);
/*绘图结束*/
?>