<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
<form action="" method="post">
<div id='add' style='width:500px;text-align:center;margin:0 auto;margin-top:50px;font-size:16px;'>
	<table width="95%" border="0" cellpadding="0" cellspacing="0">
	  <tr>
	    <td height="35" colspan="2" align="center">我要提问<div id="message" style="color: #f00;font-size:12px;"><br><?php echo $this->message;?></div></td>
	  </tr>
	  <tr>
	    <td width="100px" height="35" align="right">姓名：<input type="hidden" name="httpurl" id="httpurl" value="<?php echo $this->http;?>" /></td>
	    <td align='left'><input type="text" name="username" id="username" /></td>
	  </tr>
	  <tr>
	    <td height="35" align="right" valign="top" style="vertical-align:top;">标题：</td>
	    <td align='left'><input type="text" name="title" id="title" size="35" /></td>
	  </tr>
	  <tr>
	    <td height="35" align="right" valign="top" style="vertical-align:top;">提问：</td>
	    <td align='left'><textarea name="content" id="content" cols="35" rows="3" style="width:300px;"></textarea></td>
	  </tr>
	  <tr>
	    <td height="35" align="right" valign="top" style="vertical-align:top;">验证码：</td>
	    <td align='left'><div class="yz" title="看不清验证码请点击">
	    <img src="<?php echo Class_Server::getOrgCode();?>/default/index/checkcodeindex/" onclick="this.src='<?php echo Class_Server::getOrgCode();?>/default/index/checkcodeindex/id/'+Math.random()*5;"/> 
	    </div></td>
	  </tr>
	  <tr>
	    <td height="35" colspan="2" align="center" style="vertical-align:middle;"><input type="submit" name="button" id="submit" value="提交" /></td>
	  </tr>
	</table>
</div>
</form>

