<form method="post" action="/<?php echo Class_Server::getOrgCode()?>/default/index/index">
	<table width="700px" border="0" cellpadding="0" cellspacing="0" style="font-size:12px">
	  <tr>
	    <td height="32" colspan="2" align="left" style="color:#f00;font-size:21px;">在线咨询<div style="font-size:12px;color:#f00;"><?php echo $this->message;?></div></td>
	  </tr> 
	  <tr>
	    <td height="32" align="right"  >标题：</td>
	    <td align='left'><input type="text" name="title" id="title" size="70" /></td>
	  </tr>
	  <tr>
	    <td height="32" align="right" style='margin-top: 10px;margin-left: 40px;float:left;'>咨询内容：</td>
	    <td align='left'><textarea name="content" id="content" cols="30" rows="5" style="width:498px;"></textarea></td>
	  </tr>
	  <tr>
	    <td width="100px" height="32" align="right">我的昵称：</td>
	    <td align='left'><input type="text" name="username" id="username" size="20" /></td>
	  </tr>
	  <tr>
	    <td height="32" align="right" valign="top" style="vertical-align:top;">验证码：</td>
	    <td align='left'>
	    <input type="text" name=captcha id="captcha" size="5" />
	    <div class="yz" title="看不清验证码请点击">
	    <img id='imgcaptcha' src="<?php echo $this->captcha;//onclick="this.src='index/captcha'"?>" /> 
	    </div></td>
	  </tr>
	  <tr>
	    <td height="32" colspan="2" align="center" style="vertical-align:middle;">
	    	<input type='hidden' name='httpurl' id='httpurl' value='<?php echo $this->http?>' />
	    	<input type="submit" name="submit" value="提交" />
	    </td>
	  </tr>
	</table>
</form>
<script type='text/javascript'>
$('#imgcaptcha').click(function(){
	$.ajax({
		type: "POST",
		url: '/<?php echo Class_Server::getOrgCode()?>/default/index/captcha/type/1',
		success: function(obj) {	
			$('#imgcaptcha').attr("src",obj);
		}
	});
	return false;
});
</script>