<form method="post" action="/<?php echo Class_Server::getOrgCode()?>/default/index/index">
	<table width="650px" border="0" cellpadding="0" cellspacing="0">
	  <tr>
	    <td height="35" colspan="2" align="center">我要提问<div style="font-size:12px;color:#f00;"><?php echo $this->message;?></div></td>
	  </tr>
	  <tr>
	    <td width="100px" height="35" align="right">姓名：</td>
	    <td align='left'><input type="text" name="username" id="username" /></td>
	  </tr>
	  <tr>
	    <td height="35" align="right" valign="top" style="vertical-align:top;">标题：</td>
	    <td align='left'><input type="text" name="title" id="title" size="35" /></td>
	  </tr>
	  <tr>
	    <td height="35" align="right" valign="top" style="vertical-align:top;">提问：</td>
	    <td align='left'><textarea name="content" id="content" cols="35" rows="3" style="width:300px;"></textarea></td>
	  </tr>
	  <tr>
	    <td height="35" colspan="2" align="center" style="vertical-align:middle;">
	    	<input type='hidden' name='httpurl' value='<?php echo $this->http?>' />
	    	<input type="submit" name="submit" value="提交" />
	    </td>
	  </tr>
	</table>
</form>
