<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
<title></title>
<script type="text/javascript" src="<?=Class_Server::libUrl()?>/lib/script/jquery-1.7.1.js"></script>
<link rel="stylesheet" href="<?=Class_Server::libUrl()?>/lib/style/admin.css" type="text/css" media="screen" rel="stylesheet">
<link rel="stylesheet" href="<?=Class_Server::extUrl()?>/reset-backend.css" type="text/css" media="screen, projection">

<script type="text/javascript" src="<?=Class_Server::extUrl()?>/jub.js"></script>
<script type="text/javascript" src="<?=Class_Server::extUrl()?>/ajax-select-grid.js"></script>
