<form action="/forum/post/add/orgcode/<?php echo $this->orgcode;?>" method="post">
<table width="95%" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td width="30%" height="35" align="right">姓名：</td>
    <td width="70%" colspan="2"><input type="text" name="question" id="question" /></td>
  </tr>
  <tr>
    <td height="35" align="right" valign="top">提问：</td>
    <td colspan="2"><textarea name="issubject" id="issubject" cols="45" rows="3"></textarea></td>
  </tr>
  <tr>
    <td height="35" colspan="3" align="center"><input type="submit" name="button" id="button" value="提交" />
    <input type="button" name="button2" id="button2" value="返回" onclick="javascript:history.go(-1);" /></td>
  </tr>
</table>
</form>